# -*- coding: utf-8 -*-
"""projeto 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2nEBdUpoacoeVJdVLWI_XQpHUjsJOUd
"""

while True:
  print("Escolha a operação:")
  print("(1) Adição")
  print("(2) Subtração")
  print("(3) Multiplicação")
  print("(4) Divisão")
  print("(5) Sair")

  escolha = input('Digite o número da opeção que deseja realizar ')

  if escolha == '5':
    print ('Saindo da calculadora! Até logo!')
    break

  if escolha != '1' and escolha != '2' and escolha != '3' and escolha != '4':
    print ('Operação inválida! Tente novamente')
    break


  num1 = float (input('Digite o primeiro número'))
  num2 = float (input('Digite o segundo número'))

  if escolha == '1':
    print ('O resultado da sua soma é', num1 + num2)
  elif escolha == '2':
    print ('O resultado da sua subtração é', num1 - num2)
  elif escolha == '3':
    print ('O resultado da sua multiplicação é', num1 * num2)
  else:
    print ('O resultado da sua divisão é', num1 / num2)

